### ISSUE TITLE
Permissions problem when trying to subscribe to SNS topic

### ISSUE THREAD

**Issue by rkosir** [s22s/astraea-opendata#2]
Hi,

I'm having issues with permissions when trying to subscribe to the SNS topic `arn:aws:sns:us-west-2:552188055668:astraea-opendata-events`. 

I'm trying to use it as a trigger for Lambda function however I'm getting 403 Authorization Error from service.
Are there any specific requirements from your side to be able to subscribe to it?

Thanks in advance,
Rok

**Comment by philvarner** [comment]
We have it configured to allow sns and lambda subscriptions:

  ```
 {
      "Sid": "allowOnlySQSandLambdaSubscription",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": [
        "SNS:Subscribe",
        "SNS:Receive"
      ],
      "Resource": "arn:aws:sns:us-west-2:791757209086:astraea-opendata-events",
      "Condition": {
        "StringEquals": {
          "SNS:Protocol": [
            "sqs",
            "lambda"
          ]
        }
      }
    }
```

If this isn't working for you, it's possible the permissions aren't set up right.  Would you be able to find out what policy Sinergise has on the Sentinel 2 SNS topics?

**Comment by rkosir** [comment]
It seems it's a bug in the documentation.

It is written that SNS topic is "arn:aws:sns:us-west-2:552188055668:astraea-opendata-events".
The correct SNS ( from upper policy ) is: "arn:aws:sns:us-west-2:791757209086:astraea-opendata-events"

With this topic subscription works

**Comment by philvarner** [comment]
Thank you for figuring that out! I have a PR in review to fix that https://github.com/awslabs/open-data-registry/pull/388
